const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
};

const ERROR_CODES = {
  MISSING_FILE: 'MISSING_FILE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  CSV_PARSE_ERROR: 'CSV_PARSE_ERROR',
  INVALID_CSV: 'INVALID_CSV',
  NO_VALID_RECORDS: 'NO_VALID_RECORDS',
  GEMINI_ERROR: 'GEMINI_ERROR',
  GEMINI_TIMEOUT: 'GEMINI_TIMEOUT',
  JSON_PARSE_ERROR: 'JSON_PARSE_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

module.exports = {
  HTTP_STATUS,
  ERROR_CODES
};
